import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getPersonalProject, personalProjects } from "@/entities/personal-project/model/data";
import { Card, Icon, PageTransition, SkillBadge } from "@/shared/ui";
import { BackLink } from "@/shared/ui/BackLink";
import { ProjectCarousel } from "@/widgets/project-carousel/ui/ProjectCarousel";
import { ProjectSkillCarousel } from "@/widgets/project-skill-carousel/ui/ProjectSkillCarousel";

interface ProjectPageProps { params: { slug: string }; }
export function generateStaticParams() { return personalProjects.map(({ slug }) => ({ slug })); }
export function generateMetadata({ params }: ProjectPageProps): Metadata { const project = getPersonalProject(params.slug); return project ? { title: `${project.name} — Соснович Иван`, description: project.description } : {}; }

export default function PersonalProjectPage({ params }: ProjectPageProps) {
	const project = getPersonalProject(params.slug);
	if (!project) notFound();
	return <PageTransition><div className="mx-auto max-w-4xl px-4 py-8 sm:px-6 lg:px-8">
		<BackLink href="/my-projects" label="К личным проектам" />
		<div className="mb-8 flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div className="flex items-center gap-4"><Image src={project.logo} alt={`Логотип ${project.name}`} width={56} height={56} className="h-14 w-14 rounded-2xl" /><div><p className="text-xs font-semibold uppercase tracking-wide text-brand-600 dark:text-brand-300">{project.status}</p><h1 className="mt-1 text-3xl font-bold">{project.name}</h1><p className="mt-1 text-sm text-slate-500 dark:text-slate-400">{project.role}</p></div></div><div className="flex flex-wrap gap-3"><a href={project.repositoryUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-slate-800 px-4 py-2 text-sm font-medium text-white hover:bg-slate-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 dark:bg-slate-700"><Icon name="github" className="h-4 w-4" />GitHub</a>{project.websiteUrl && <a href={project.websiteUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-2 rounded-lg bg-brand-600 px-4 py-2 text-sm font-medium text-white hover:bg-brand-700 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500"><Icon name="external-link" className="h-4 w-4" />Открыть сайт</a>}</div></div>
		<nav aria-label="Разделы кейса" className="sticky top-[65px] z-30 mb-8 flex gap-1 overflow-x-auto rounded-xl border border-slate-200 bg-white/90 p-1.5 shadow-sm backdrop-blur dark:border-slate-700 dark:bg-slate-900/90">{[["overview", "Контекст"], ["role", "Моя роль"], [project.benefitSkills ? "evidence" : "screens", project.benefitSkills ? "Результаты" : "Экраны"], ["architecture", "Архитектура"]].map(([href, label]) => <a key={href} href={`#${href}`} className="shrink-0 rounded-lg px-3 py-2 text-sm font-medium text-slate-600 hover:bg-brand-50 hover:text-brand-600 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-brand-500 dark:text-slate-300 dark:hover:bg-brand-950">{label}</a>)}</nav>
		<Card id="overview" className="scroll-mt-32 border-brand-200 p-6 dark:border-brand-900"><p className="text-xs font-semibold uppercase tracking-wide text-brand-600 dark:text-brand-300">Контекст и результат</p><h2 className="mt-2 text-2xl font-bold leading-tight text-slate-950 dark:text-white">{project.featuredResult}</h2><p className="mt-4 leading-relaxed text-slate-700 dark:text-slate-200">{project.description}</p><div className="mt-5 flex items-start gap-3 rounded-xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-700 dark:bg-slate-950"><Icon name="sparkles" className="mt-0.5 h-5 w-5 shrink-0 text-brand-600 dark:text-brand-300" /><div><p className="text-xs font-semibold uppercase tracking-wide text-brand-600 dark:text-brand-300">AI-assisted процесс</p><p className="mt-1 text-sm font-medium leading-relaxed text-slate-800 dark:text-slate-100">{project.creationProcess}</p></div></div></Card>
		<section id="role" className="scroll-mt-32 py-8"><h2 className="mb-4 text-xl font-semibold">Моя зона ответственности</h2><div className="grid gap-4 md:grid-cols-3">{project.contribution.map((item) => <Card key={item.title} className="p-5"><h3 className="font-semibold text-slate-900 dark:text-white">{item.title}</h3><p className="mt-2 text-sm leading-relaxed text-slate-600 dark:text-slate-300">{item.description}</p></Card>)}</div></section>
		{project.benefitSkills ? <section id="evidence" className="scroll-mt-32 pb-8"><h2 className="mb-4 text-xl font-semibold">Skills с подтверждённой пользой</h2><ProjectSkillCarousel skills={project.benefitSkills} projectName={project.name} /></section> : project.screenshots.length > 0 && <section id="screens" className="scroll-mt-32 pb-8"><h2 className="mb-1 text-xl font-semibold">Экраны проекта</h2><p className="mb-4 text-sm text-slate-500 dark:text-slate-400">Каждый кадр можно открыть в полном размере; также работают клавиши ← и →.</p><ProjectCarousel images={project.screenshots} title={project.name} /></section>}
		<section id="architecture" className="scroll-mt-32"><Card className="mb-8 p-6"><p className="text-xs font-semibold uppercase tracking-wide text-brand-600 dark:text-brand-300">Схема решения</p><h2 className="mt-1 text-xl font-semibold text-slate-950 dark:text-white">Архитектура</h2><div className="my-5 flex flex-col items-stretch gap-2 sm:flex-row sm:items-center">{project.architectureFlow.map((node, index) => <div key={node} className="contents"><div className="flex-1 rounded-xl border-2 border-slate-300 bg-white px-3 py-3 text-center text-sm font-bold text-slate-950 shadow-sm dark:border-slate-600 dark:bg-slate-950 dark:text-white">{node}</div>{index < project.architectureFlow.length - 1 && <Icon name="arrow-right" className="mx-auto h-4 w-4 rotate-90 shrink-0 text-brand-600 sm:rotate-0 dark:text-brand-300" />}</div>)}</div><ul className="space-y-3">{project.architecture.map((item) => <li key={item} className="flex gap-3 text-sm leading-relaxed text-slate-700 dark:text-slate-200"><Icon name="check" className="mt-0.5 h-5 w-5 shrink-0 text-success-600 dark:text-success-400" />{item}</li>)}</ul></Card></section>
		<Card className="p-6"><h2 className="mb-4 text-xl font-semibold">Технологии</h2><div className="flex flex-wrap gap-2">{project.technologies.map((technology) => <SkillBadge key={technology} skill={technology} />)}</div></Card>
		<Link href="/my-projects" className="mt-8 inline-flex items-center gap-2 text-sm font-medium text-brand-600 hover:text-brand-700 dark:text-brand-300"><Icon name="arrow-left" className="h-4 w-4" />Ко всем личным проектам</Link>
	</div></PageTransition>;
}
